export const UK_CITIES = [
	{ city: "London" },
	{ city: "Manchester" },
	{ city: "Birmingham" },
	{ city: "Liverpool" },
	{ city: "Leeds" },
	{ city: "Sheffield" },
	{ city: "Bristol" },
	{ city: "Edinburgh" },
	{ city: "Glasgow" },
	{ city: "Cardiff" },
	{ city: "Nottingham" },
	{ city: "Leicester" },
	{ city: "Newcastle" },
	{ city: "Brighton" },
	{ city: "Oxford" },
	{ city: "Cambridge" },
	{ city: "York" },
	{ city: "Bath" },
	{ city: "Canterbury" },
	{ city: "Bournemouth" },
	{ city: "Southampton" },
	{ city: "Portsmouth" },
	{ city: "Southampton" },
];
